### ISSUE TITLE
Panic when running `lporg load`

### ISSUE THREAD

**Issue by 5ouma** [blacktop/lporg#32]
When running `lp.DB.Where("type in (?)", []int{RootType, FolderRootType, PageType})`, it's panic and can't operate launchpad

https://github.com/blacktop/lporg/blob/23a07c094132fe61c789ad9c5ae5bece95a2e5a8/internal/database/database.go#L82-L88

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x121e452]

goroutine 1 [running]:
gorm.io/gorm.(*DB).getInstance(0x1a3e108?)
	gorm.io/gorm@v1.25.4/gorm.go:399 +0x12
gorm.io/gorm.(*DB).Where(0xc0000187e0?, {0x14e8d40, 0x1610a90}, {0xc00032a730, 0x1, 0x1})
	gorm.io/gorm@v1.25.4/chainable_api.go:201 +0x36
github.com/blacktop/lporg/internal/database.(*LaunchPad).ClearGroups(0xc000407b88)
	github.com/blacktop/lporg/internal/database/database.go:87 +0x109
github.com/blacktop/lporg/internal/command.LoadConfig(0xc00013dcd8)
	github.com/blacktop/lporg/internal/command/command.go:415 +0x66e
github.com/blacktop/lporg/cmd.glob..func2(0xc0001d4200?, {0xc00014d730?, 0x4?, 0x15567a2?})
	github.com/blacktop/lporg/cmd/load.go:56 +0x1ad
github.com/spf13/cobra.(*Command).execute(0x192fb20, {0xc00014d710, 0x1, 0x1})
	github.com/spf13/cobra@v1.7.0/command.go:940 +0x87c
github.com/spf13/cobra.(*Command).ExecuteC(0x19300e0)
	github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3a5
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.7.0/command.go:992
github.com/blacktop/lporg/cmd.Execute()
	github.com/blacktop/lporg/cmd/root.go:61 +0x1a
main.main()
	github.com/blacktop/lporg/main.go:27 +0xf
```

**Comment by blacktop** [comment]
does this still happen w/ the latest release?

**Comment by 5ouma** [comment]
There is no panic, but it exits with no messages.

**Comment by blacktop** [comment]
How are you running it? You might have to download the latest release. I released MANY times yesterday

**Comment by blacktop** [comment]
My apologies, I've changed too many things all at the same time.  Please try again with the latest version

**Comment by blacktop** [comment]
https://github.com/blacktop/lporg/releases/tag/v20.4.21

**Comment by 5ouma** [comment]
This is fixed!!
Thank you very much.
