### ISSUE TITLE
Panic with `default` sub-command

### ISSUE THREAD

**Issue by silver886** [blacktop/lporg#47]
In version 20.4.27, `default` cannot exit peacefully.
However, it does restore to default somehow.

Here is the log:
```shellsession
panic: interface conversion: interface {} is database.AppFolder, not map[string]interface {}

goroutine 1 [running]:
github.com/blacktop/lporg/internal/database.(*LaunchPad).GetMissing(0xc00049db00, 0xc00049da10, 0x3?)
	github.com/blacktop/lporg/internal/database/database.go:104 +0xf0e
github.com/blacktop/lporg/internal/command.DefaultOrg(0xc00049dca8)
	github.com/blacktop/lporg/internal/command/command.go:260 +0xdfc
github.com/blacktop/lporg/cmd.glob..func1(0x19b3040, {0x19e8700?, 0x4?, 0x1594782?})
	github.com/blacktop/lporg/cmd/default.go:101 +0x491
github.com/spf13/cobra.(*Command).execute(0x19b3040, {0x19e8700, 0x0, 0x0})
	github.com/spf13/cobra@v1.7.0/command.go:940 +0x87c
github.com/spf13/cobra.(*Command).ExecuteC(0x19b38e0)
	github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3a5
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.7.0/command.go:992
github.com/blacktop/lporg/cmd.Execute()
	github.com/blacktop/lporg/cmd/root.go:61 +0x1a
main.main()
	github.com/blacktop/lporg/main.go:27 +0xf
```

**Comment by blacktop** [comment]
please try latest

**Comment by silver886** [comment]
It works just fine at version 20.4.30.
