### ISSUE TITLE
Compatibility with macOS Big Sur

### ISSUE THREAD

**Issue by maephisto666** [blacktop/lporg#8]
Hello, I saw in the readme that `lporg` has been tested on macOS High Sierra. I am wondering, is this "supposed" to work on macOS Big Sur? 

After installing `lporg`, I ran `lporg save` and I got the following error but I'm not sure if this is because of macOS Big Sur or other reasons.
```
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0xb01dfacedebac1e pc=0x7fff2040ac9e]

runtime stack:
runtime: unexpected return pc for runtime.sigpanic called from 0x7fff2040ac9e
stack: frame={sp:0x7ffeefbff1d8, fp:0x7ffeefbff228} stack=[0x7ffeefb80278,0x7ffeefbff2e0)
0x00007ffeefbff0d8:  0x01007ffeefbff0f8  0x0000000000000004
0x00007ffeefbff0e8:  0x000000000000001f  0x00007fff2040ac9e
0x00007ffeefbff0f8:  0x0b01dfacedebac1e  0x0000000000000001
0x00007ffeefbff108:  0x0000000004035df1 <runtime.throw+0x0000000000000071>  0x00007ffeefbff1a8
0x00007ffeefbff118:  0x000000000440d227  0x00007ffeefbff160
0x00007ffeefbff128:  0x00000000040360a8 <runtime.fatalthrow.func1+0x0000000000000048>  0x0000000004641540
0x00007ffeefbff138:  0x0000000000000001  0x0000000000000001
0x00007ffeefbff148:  0x00007ffeefbff1a8  0x0000000004035df1 <runtime.throw+0x0000000000000071>
0x00007ffeefbff158:  0x0000000004641540  0x00007ffeefbff198
0x00007ffeefbff168:  0x0000000004036030 <runtime.fatalthrow+0x0000000000000050>  0x00007ffeefbff178
0x00007ffeefbff178:  0x0000000004036060 <runtime.fatalthrow.func1+0x0000000000000000>  0x0000000004641540
0x00007ffeefbff188:  0x0000000004035df1 <runtime.throw+0x0000000000000071>  0x00007ffeefbff1a8
0x00007ffeefbff198:  0x00007ffeefbff1c8  0x0000000004035df1 <runtime.throw+0x0000000000000071>
0x00007ffeefbff1a8:  0x00007ffeefbff1b0  0x0000000004035e20 <runtime.throw.func1+0x0000000000000000>
0x00007ffeefbff1b8:  0x0000000004411a8a  0x000000000000002a
0x00007ffeefbff1c8:  0x00007ffeefbff218  0x000000000404b596 <runtime.sigpanic+0x0000000000000396>
0x00007ffeefbff1d8: <0x0000000004411a8a  0x0000000004641540
0x00007ffeefbff1e8:  0x00007ffeefbff258  0x0000000000000000
0x00007ffeefbff1f8:  0x00000000046416e0  0x0000000000000000
0x00007ffeefbff208:  0x000000c000240ee8  0x00000000040a9000 <syscall.libc_write_trampoline+0x0000000000000000>
0x00007ffeefbff218:  0x00007ffeefbff260 !0x00007fff2040ac9e
0x00007ffeefbff228: >0x00007ffeefbff260  0x0000000004614000
0x00007ffeefbff238:  0x00000000000003be  0x0000000004139b65 <golang.org/x/sys/unix.libc_ioctl_trampoline+0x0000000000000005>
0x00007ffeefbff248:  0x000000000406769f <runtime.syscall+0x000000000000001f>  0x000000c000240e60
0x00007ffeefbff258:  0x00000000046416e0  0x000000c000240e30
0x00007ffeefbff268:  0x0000000004065510 <runtime.asmcgocall+0x0000000000000070>  0x00007ffeefbff2a0
0x00007ffeefbff278:  0x000000000401062e <runtime.persistentalloc.func1+0x000000000000002e>  0x0000000000000020
0x00007ffeefbff288:  0x0000000000000000  0x0000000004671ae0
0x00007ffeefbff298:  0x00000000000011f8  0x000000c0000001a0
0x00007ffeefbff2a8:  0x0000000004063629 <runtime.systemstack+0x0000000000000049>  0x0000000000000004
0x00007ffeefbff2b8:  0x00000000044611a0  0x0000000004641540
0x00007ffeefbff2c8:  0x00007ffeefbff310  0x0000000004063525 <runtime.mstart+0x0000000000000005>
0x00007ffeefbff2d8:  0x00000000040634dd <runtime.rt0_go+0x000000000000013d>
runtime.throw({0x4411a8a, 0x4641540})
	/opt/homebrew/Cellar/go/1.17.3/libexec/src/runtime/panic.go:1198 +0x71
runtime: unexpected return pc for runtime.sigpanic called from 0x7fff2040ac9e
stack: frame={sp:0x7ffeefbff1d8, fp:0x7ffeefbff228} stack=[0x7ffeefb80278,0x7ffeefbff2e0)
0x00007ffeefbff0d8:  0x01007ffeefbff0f8  0x0000000000000004
0x00007ffeefbff0e8:  0x000000000000001f  0x00007fff2040ac9e
0x00007ffeefbff0f8:  0x0b01dfacedebac1e  0x0000000000000001
0x00007ffeefbff108:  0x0000000004035df1 <runtime.throw+0x0000000000000071>  0x00007ffeefbff1a8
0x00007ffeefbff118:  0x000000000440d227  0x00007ffeefbff160
0x00007ffeefbff128:  0x00000000040360a8 <runtime.fatalthrow.func1+0x0000000000000048>  0x0000000004641540
0x00007ffeefbff138:  0x0000000000000001  0x0000000000000001
0x00007ffeefbff148:  0x00007ffeefbff1a8  0x0000000004035df1 <runtime.throw+0x0000000000000071>
0x00007ffeefbff158:  0x0000000004641540  0x00007ffeefbff198
0x00007ffeefbff168:  0x0000000004036030 <runtime.fatalthrow+0x0000000000000050>  0x00007ffeefbff178
0x00007ffeefbff178:  0x0000000004036060 <runtime.fatalthrow.func1+0x0000000000000000>  0x0000000004641540
0x00007ffeefbff188:  0x0000000004035df1 <runtime.throw+0x0000000000000071>  0x00007ffeefbff1a8
0x00007ffeefbff198:  0x00007ffeefbff1c8  0x0000000004035df1 <runtime.throw+0x0000000000000071>
0x00007ffeefbff1a8:  0x00007ffeefbff1b0  0x0000000004035e20 <runtime.throw.func1+0x0000000000000000>
0x00007ffeefbff1b8:  0x0000000004411a8a  0x000000000000002a
0x00007ffeefbff1c8:  0x00007ffeefbff218  0x000000000404b596 <runtime.sigpanic+0x0000000000000396>
0x00007ffeefbff1d8: <0x0000000004411a8a  0x0000000004641540
0x00007ffeefbff1e8:  0x00007ffeefbff258  0x0000000000000000
0x00007ffeefbff1f8:  0x00000000046416e0  0x0000000000000000
0x00007ffeefbff208:  0x000000c000240ee8  0x00000000040a9000 <syscall.libc_write_trampoline+0x0000000000000000>
0x00007ffeefbff218:  0x00007ffeefbff260 !0x00007fff2040ac9e
0x00007ffeefbff228: >0x00007ffeefbff260  0x0000000004614000
0x00007ffeefbff238:  0x00000000000003be  0x0000000004139b65 <golang.org/x/sys/unix.libc_ioctl_trampoline+0x0000000000000005>
0x00007ffeefbff248:  0x000000000406769f <runtime.syscall+0x000000000000001f>  0x000000c000240e60
0x00007ffeefbff258:  0x00000000046416e0  0x000000c000240e30
0x00007ffeefbff268:  0x0000000004065510 <runtime.asmcgocall+0x0000000000000070>  0x00007ffeefbff2a0
0x00007ffeefbff278:  0x000000000401062e <runtime.persistentalloc.func1+0x000000000000002e>  0x0000000000000020
0x00007ffeefbff288:  0x0000000000000000  0x0000000004671ae0
0x00007ffeefbff298:  0x00000000000011f8  0x000000c0000001a0
0x00007ffeefbff2a8:  0x0000000004063629 <runtime.systemstack+0x0000000000000049>  0x0000000000000004
0x00007ffeefbff2b8:  0x00000000044611a0  0x0000000004641540
0x00007ffeefbff2c8:  0x00007ffeefbff310  0x0000000004063525 <runtime.mstart+0x0000000000000005>
0x00007ffeefbff2d8:  0x00000000040634dd <runtime.rt0_go+0x000000000000013d>
runtime.sigpanic()
	/opt/homebrew/Cellar/go/1.17.3/libexec/src/runtime/signal_unix.go:719 +0x396

goroutine 1 [syscall]:
syscall.syscall(0x4139b60, 0x1, 0x40087468, 0xc000240ef0)
	/opt/homebrew/Cellar/go/1.17.3/libexec/src/runtime/sys_darwin.go:22 +0x3b fp=0xc000240e60 sp=0xc000240e40 pc=0x40621db
syscall.syscall(0x80000000000, 0xc000240ec8, 0x40c17c6, 0xc00006c0c0)
	<autogenerated>:1 +0x26 fp=0xc000240ea8 sp=0xc000240e60 pc=0x4067e66
golang.org/x/sys/unix.ioctl(0xc00006c0c0, 0xc00000a700, 0x40a9000)
	/Users/blacktop/go/pkg/mod/golang.org/x/sys@v0.0.0-20201119102817-f84b799fce68/unix/zsyscall_darwin_amd64.go:731 +0x39 fp=0xc000240ed8 sp=0xc000240ea8 pc=0x41397f9
golang.org/x/sys/unix.IoctlGetWinsize(...)
	/Users/blacktop/go/pkg/mod/golang.org/x/sys@v0.0.0-20201119102817-f84b799fce68/unix/ioctl.go:66
golang.org/x/term.getSize(0x2)
	/Users/blacktop/go/pkg/mod/golang.org/x/term@v0.0.0-20210503060354-a79de5458b56/term_unix.go:61 +0x2c fp=0xc000240f08 sp=0xc000240ed8 pc=0x4139bec
golang.org/x/term.GetSize(...)
	/Users/blacktop/go/pkg/mod/golang.org/x/term@v0.0.0-20210503060354-a79de5458b56/term.go:50
github.com/AlecAivazis/survey/v2.(*Renderer).termWidth(0x43affc0)
	/Users/blacktop/go/pkg/mod/github.com/!alec!aivazis/survey/v2@v2.3.2/renderer.go:145 +0x28 fp=0xc000240f20 sp=0xc000240f08 pc=0x413b4c8
github.com/AlecAivazis/survey/v2.(*Renderer).termWidthSafe(...)
	/Users/blacktop/go/pkg/mod/github.com/!alec!aivazis/survey/v2@v2.3.2/renderer.go:150
github.com/AlecAivazis/survey/v2.(*Renderer).countLines(0x4079a8f, {{0x0, 0x0, 0x0}, 0x0, 0x0})
	/Users/blacktop/go/pkg/mod/github.com/!alec!aivazis/survey/v2@v2.3.2/renderer.go:162 +0x45 fp=0xc000240f98 sp=0xc000240f20 pc=0x413b545
github.com/AlecAivazis/survey/v2.(*Renderer).Render(0xc000136fc0, {0x44171bf, 0x3a0}, {0x43ec660, 0xc00015c900})
	/Users/blacktop/go/pkg/mod/github.com/!alec!aivazis/survey/v2@v2.3.2/renderer.go:82 +0xa5 fp=0xc000241040 sp=0xc000240f98 pc=0x413ae25
github.com/AlecAivazis/survey/v2.(*Renderer).RenderWithCursorOffset(0xc000136fc0, {0x44171bf, 0x3a0}, {0x4465b80, 0xc00015c900}, {0xc0001d9020, 0x2, 0x2}, 0x4721108)
	/Users/blacktop/go/pkg/mod/github.com/!alec!aivazis/survey/v2@v2.3.2/renderer.go:106 +0x11d fp=0xc0002410d8 sp=0xc000241040 pc=0x413b0bd
github.com/AlecAivazis/survey/v2.(*Select).Prompt(0xc000136fc0, 0xc0001e8468)
	/Users/blacktop/go/pkg/mod/github.com/!alec!aivazis/survey/v2@v2.3.2/select.go:266 +0x44a fp=0xc000241648 sp=0xc0002410d8 pc=0x413c5aa
github.com/AlecAivazis/survey/v2.Ask({0xc0002417c8, 0x1, 0x46371c0}, {0x43a8b20, 0xc000209340}, {0xc0002417c0, 0x1, 0x0})
	/Users/blacktop/go/pkg/mod/github.com/!alec!aivazis/survey/v2@v2.3.2/survey.go:308 +0x214 fp=0xc000241760 sp=0xc000241648 pc=0x413d434
github.com/AlecAivazis/survey/v2.AskOne(...)
	/Users/blacktop/go/pkg/mod/github.com/!alec!aivazis/survey/v2@v2.3.2/survey.go:251
main.main.func2(0xc0001e82c0)
	/Users/blacktop/Projects/Github/blacktop/lporg/launch.go:543 +0x17e fp=0xc000241818 sp=0xc000241760 pc=0x4271c3e
github.com/urfave/cli.HandleAction({0x43b3c80, 0x441a260}, 0x4)
	/Users/blacktop/go/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:524 +0xa8 fp=0xc000241830 sp=0xc000241818 pc=0x4259328
github.com/urfave/cli.Command.Run({{0x43ff9ce, 0x4}, {0x0, 0x0}, {0x0, 0x0, 0x0}, {0x440d645, 0x1f}, {0x0, ...}, ...}, ...)
	/Users/blacktop/go/pkg/mod/github.com/urfave/cli@v1.22.5/command.go:173 +0x652 fp=0xc000241a10 sp=0xc000241830 pc=0x425a112
github.com/urfave/cli.(*App).Run(0xc00013c380, {0xc000012040, 0x2, 0x2})
	/Users/blacktop/go/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:277 +0x705 fp=0xc000241d50 sp=0xc000241a10 pc=0x42574e5
main.main()
	/Users/blacktop/Projects/Github/blacktop/lporg/launch.go:613 +0x812 fp=0xc000241f80 sp=0xc000241d50 pc=0x4270d32
runtime.main()
	/opt/homebrew/Cellar/go/1.17.3/libexec/src/runtime/proc.go:255 +0x227 fp=0xc000241fe0 sp=0xc000241f80 pc=0x4038487
runtime.goexit()
	/opt/homebrew/Cellar/go/1.17.3/libexec/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc000241fe8 sp=0xc000241fe0 pc=0x4065801
```

**Comment by blacktop** [comment]
what version of lporg are you running?

**Comment by blacktop** [comment]
the stack trace seems to be having issues with you terminal size?

**Comment by blacktop** [comment]
it might have been an issue in the google sys pkg?  I've updated the deps and uploaded a new version.

**Comment by maephisto666** [comment]
Thank you @blacktop.

Sorry for the late response.
I was using the version `20.4.6`.
After your update, I can now confirm that version `20.4.7` is working for me. I'm running macOS Big Sur 11.6.1

**Comment by blacktop** [comment]
glad to hear it! 👍
